name: Create Enix Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Plugin ZIP
        run: |
          mkdir enix-addons-for-elementor
          rsync -rr --exclude='.git/' --exclude='.github/' --exclude='enix-addons-for-elementor' ./ enix-addons-for-elementor/
          zip -r enix-addons-for-elementor.zip enix-addons-for-elementor/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: enix-addons-for-elementor.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
